### ISSUE TITLE
Nice job but ...

### ISSUE THREAD

**Issue by WebCrew** [mentionbb/mentionbb#3]
### Hi Devs,

First of all, I would like to say **please don't lose heart**, even if it doesn't work right from the start that hundreds of people are immediately interested in your forum CMS and the "stars" on GitHub don't grow quickly either. **I think you have something good and very interesting going on** and the design looks really **fantastic** and, above all, modern and contemporary, **not some old PHPBB elephant**.

I would like you to **make it as easy as possible for the few people who are still interested**, especially at the beginning, **and develop a classic PHP installer for it as quickly as possible**. I think this helps many people decide to give the forum a try. People are lazy as hell these days and if devs like us want to have some success we have to sadly support their lazyness. 

**PHP Installer Edample:**
[phpInstallerScript.zip](https://github.com/mentionbb/mentionbb/files/15313721/phpInstallerScript.zip)

Either way, **I wish you much success** and I think you will too if you are patient until the word finally gets around.

**Greetings** Andreas (WebCrew)

**Comment by par274** [comment]
Thank you for your good wishes.

I am currently developing an Installer for the project. But it's progressing slowly because I'm concentrating on other features. There is currently code written for the Installer in the project, but as I said, it is being developed slowly.

https://github.com/mentionbb/mentionbb/tree/master/src/Install

You can see the install files, which we can call "beta", among the files here. The install will definitely be released within this year.

**Comment by WebCrew** [comment]
Sounds good  :cowboy_hat_face:

If I find some time I`ll check out the language files and create a german translation of it.

Have a nice day and good luck and much success.

**Comment by par274** [comment]
I would be happy to add the German translation to the project.

Thanks again.
